# Generated by Django 5.1.7 on 2025-03-20 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('departure_airport', models.CharField(max_length=3)),
                ('arrival_airport', models.CharField(max_length=3)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('stops', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='flights.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerarie',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=5)),
                ('agent', models.CharField(max_length=20)),
                ('agent_rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legs', models.ManyToManyField(related_name='itineraries', to='flights.leg')),
            ],
        ),
    ]
